name: ht_crud_api
description: A generic Dart package providing a reusable CrudApi class for interacting with RESTful endpoints via ht_http_client.
repository: https://github.com/headlines-toolkit/ht-crud-api
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ht_crud_client:
    git:
      url: https://github.com/headlines-toolkit/ht-crud-client.git
  ht_http_client:
    git:
      url: https://github.com/headlines-toolkit/ht-http-client.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^7.0.0
