name: data_api
description: A generic Dart package providing an implementation of DataClient for interacting with data resource endpoints via http_client.
repository: https://github.com/flutter-news-app-full-source-code/data-api
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  data_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-client.git
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^9.0.0
